//This file is generated by bin/hook.js
var template = require('lodash.template');
module.exports = {

  'channels': template('<div class="channels" data-channels>	<ul data-channels-list>		<% for(var c in channels) { %>		<li data-channel-choice>			<a href="#channel-<%= c %>" data-id="<%= c %>">				<img src="<%= channels[c].poster %>" alt="<%= channels[c].name %>" />			</a>		</li>		<% } %>	</ul></div>'),

  CSS: {
    
      'channels': '.player-channels[data-channels]{position:absolute;width:100%;height:100%;top:0;left:0;z-index:1}.player-channels[data-channels] ul[data-channels-list]{margin:0;padding:2.5% 0 0 2.5%;width:20%;list-style-type:none}.player-channels[data-channels] ul[data-channels-list] li[data-channel-choice] a{display:block;width:100%;height:100%;margin-bottom:12.5%;border:2px solid #fff}.player-channels[data-channels] ul[data-channels-list] li[data-channel-choice] a:hover{-webkit-box-shadow:#fff 0 0 25px,#fff 0 0 3px 1px inset;-moz-box-shadow:#fff 0 0 25px,#fff 0 0 3px 1px inset;-ms-box-shadow:#fff 0 0 25px,#fff 0 0 3px 1px inset;-o-box-shadow:#fff 0 0 25px,#fff 0 0 3px 1px inset;box-shadow:#fff 0 0 25px,#fff 0 0 3px 1px inset}.player-channels[data-channels] ul[data-channels-list] li[data-channel-choice] a img{display:block;max-width:100%;height:auto}',
    
  }
};
